version: 2
updates:
  # Update Rust dependencies in workspace root
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    groups:
      serde:
        patterns:
          - "serde*"
      test-deps:
        patterns:
          - "proptest"
          - "criterion"

  # Update Rust dependencies in logisim_core crate
  - package-ecosystem: "cargo"
    directory: "/logisim_core"
    schedule:
      interval: "weekly"
    target-branch: "main"

  # Keep GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
