[workspace]
members = ["logisim_core"]
resolver = "2"

[workspace.dependencies]
# Common dependencies can be defined here
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
quick-xml = { version = "0.32", features = ["serialize"] }
roxmltree = "0.20"