name: "Rust Build & Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  analyze_sources:
    name: "Check for Rust source changes"
    runs-on: ubuntu-latest
    outputs:
      run_build: ${{ steps.filter.outputs.rust }}
    
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v4
    
    - name: "Look for changes in Rust code"
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          rust:
            - '**/*.rs'
            - '**/Cargo.toml'
            - '**/Cargo.lock'
            - 'rust-toolchain.toml'
    
    - name: "Will build step run?"
      run: |
        found="NO"
        [[ ${{ steps.filter.outputs.rust }} == 'true' ]] && found="YES"
        echo "run_build=${found}" >> $GITHUB_OUTPUT
        echo "Build step will run: ${found}"

  build_and_test:
    name: "Build and Test"
    runs-on: ${{ matrix.os }}
    needs: analyze_sources
    if: needs.analyze_sources.outputs.run_build == 'true'
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta]
        exclude:
          # Only run beta on Ubuntu to reduce CI load
          - os: windows-latest
            rust: beta
          - os: macos-latest
            rust: beta
    
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v4
    
    - name: "Install Rust toolchain"
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
    
    - name: "Cache Rust dependencies"
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    
    - name: "Check code formatting"
      run: cargo fmt --all -- --check
    
    - name: "Run Clippy"
      run: cargo clippy --all-targets --all-features -- -D warnings
    
    - name: "Build workspace"
      run: cargo build --verbose --all-features
    
    - name: "Run tests"
      run: cargo test --verbose --all-features
    
    - name: "Build documentation"
      run: cargo doc --verbose --all-features --no-deps
    
    - name: "Run doc tests"
      run: cargo test --doc --verbose --all-features

  coverage:
    name: "Code Coverage"
    runs-on: ubuntu-latest
    needs: analyze_sources
    if: needs.analyze_sources.outputs.run_build == 'true'
    
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v4
    
    - name: "Install Rust toolchain"
      uses: dtolnay/rust-toolchain@stable
    
    - name: "Cache Rust dependencies"
      uses: Swatinem/rust-cache@v2
    
    - name: "Install cargo-tarpaulin"
      run: cargo install cargo-tarpaulin
    
    - name: "Generate code coverage"
      run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
    
    - name: "Upload to codecov.io"
      uses: codecov/codecov-action@v5
      with:
        file: cobertura.xml
        fail_ci_if_error: false